from dataclasses import dataclass, field

from robot_skills import (
    RobotSkills,
    ActionResult,
)


# ==========================================================
# TASK 3 -> TASK 4 VOCABULARY NORMALISATION
# ==========================================================

# Task 3 is language-based and may refer to the same
# simulator object using different natural-language names.
#
# Task 4 uses one canonical internal name for each object.

OBJECT_ALIASES = {

    # ------------------------------------------------------
    # BOX
    # ------------------------------------------------------

    "box": "box",
    "blue box": "box",
    "blue_box": "box",
    "cube": "box",
    "blue cube": "box",
    "blue_cube": "box",

    # ------------------------------------------------------
    # CYLINDER
    # ------------------------------------------------------

    "cylinder": "cylinder",
    "green cylinder": "cylinder",
    "green_cylinder": "cylinder",

    # ------------------------------------------------------
    # STONE
    # ------------------------------------------------------

    "stone": "stone",
    "rock": "stone",
    "grey stone": "stone",
    "gray stone": "stone",
    "sphere": "stone",
    "grey sphere": "stone",
    "gray sphere": "stone",
}


TARGET_ALIASES = {

    "red_area": "red_area",
    "red area": "red_area",
    "red zone": "red_area",
    "red region": "red_area",
    "red target": "red_area",
    "target area": "red_area",
    "target_area": "red_area",
}


# ==========================================================
# EXECUTION REPORT
# ==========================================================

@dataclass
class ExecutionReport:
    """
    Summary of one complete structured plan execution.
    """

    success: bool

    completed_actions: int

    total_actions: int

    results: list = field(
        default_factory=list
    )

    failure_reason: str | None = None

    final_placement_error: float | None = None

    grasp_attempts: int = 0


# ==========================================================
# TASK 4 EXECUTOR
# ==========================================================

class Task4Executor:

    def __init__(
        self,
        robot=None,
    ):

        if robot is None:

            self.robot = (
                RobotSkills()
            )

        else:

            self.robot = robot

        # --------------------------------------------------
        # Execution context
        # --------------------------------------------------

        # Remembers the object successfully grasped most
        # recently. This is important because Task 3 may
        # output:
        #
        #     PLACE red_area
        #
        # rather than:
        #
        #     PLACE box red_area

        self.last_grasped_object = None

        self.last_target_region = None

        self.last_placed_object = None

        self.execution_results = []

    # ======================================================
    # START
    # ======================================================

    def start(self):

        if self.robot.viewer is None:

            self.robot.start_viewer()

    # ======================================================
    # NAME NORMALISATION
    # ======================================================

    def normalise_object_name(
        self,
        name,
    ):
        """
        Convert natural-language object names generated by
        Task 3 into the canonical names expected by Task 4.

        Examples:

            "blue box" -> "box"
            "rock" -> "stone"
            "green cylinder" -> "cylinder"
        """

        if name is None:

            return None

        key = (
            str(name)
            .strip()
            .lower()
        )

        return OBJECT_ALIASES.get(
            key,
            key,
        )

    def normalise_target_name(
        self,
        name,
    ):
        """
        Convert natural-language target names generated by
        Task 3 into canonical Task 4 target names.

        Examples:

            "red area" -> "red_area"
            "red zone" -> "red_area"
        """

        if name is None:

            return None

        key = (
            str(name)
            .strip()
            .lower()
        )

        return TARGET_ALIASES.get(
            key,
            key,
        )

    # ======================================================
    # ACTION DISPATCH
    # ======================================================

    def execute_action(
        self,
        action,
    ):
        """
        Convert one structured Task 3 action into a
        physical Task 4 robot behaviour.
        """

        # --------------------------------------------------
        # Validate action
        # --------------------------------------------------

        if not isinstance(
            action,
            dict,
        ):

            return ActionResult(
                success=False,
                skill="INVALID",
                message=(
                    "Action must be "
                    "a dictionary"
                ),
            )

        skill = action.get(
            "skill"
        )

        if skill is None:

            return ActionResult(
                success=False,
                skill="INVALID",
                message=(
                    "Action has no skill field"
                ),
            )

        skill = (
            str(skill)
            .strip()
            .upper()
        )

        print(
            "\n"
            + "#" * 60
        )

        print(
            f"TASK 4 EXECUTOR: {skill}"
        )

        print(
            "Action:",
            action,
        )

        print(
            "#" * 60
        )

        # ==================================================
        # SEARCH
        # ==================================================

        if skill == "SEARCH":

            target = (
                self.normalise_object_name(
                    action.get(
                        "target"
                    )
                )
            )

            if not target:

                return ActionResult(
                    success=False,
                    skill="SEARCH",
                    message=(
                        "SEARCH requires "
                        "a target"
                    ),
                )

            print(
                "Normalised search target:",
                target,
            )

            # Use the Task 4 search behaviour.
            #
            # With current simulator-state grounding,
            # objects normally appear immediately available.
            #
            # Once Task 2 is connected, this same search
            # state machine can use wrist-camera visibility.

            return self.robot.search(
                target
            )

        # ==================================================
        # APPROACH
        # ==================================================

        if skill == "APPROACH":

            target = (
                self.normalise_object_name(
                    action.get(
                        "target"
                    )
                )
            )

            if not target:

                return ActionResult(
                    success=False,
                    skill="APPROACH",
                    message=(
                        "APPROACH requires "
                        "a target"
                    ),
                )

            print(
                "Normalised approach target:",
                target,
            )

            return self.robot.approach(
                target
            )

        # ==================================================
        # REACH
        # ==================================================

        if skill == "REACH":

            target = (
                self.normalise_object_name(
                    action.get(
                        "target"
                    )
                )
            )

            if not target:

                return ActionResult(
                    success=False,
                    skill="REACH",
                    message=(
                        "REACH requires "
                        "a target"
                    ),
                )

            print(
                "Normalised reach target:",
                target,
            )

            return self.robot.reach(
                target
            )

        # ==================================================
        # GRASP
        # ==================================================

        if skill == "GRASP":

            target = (
                self.normalise_object_name(
                    action.get(
                        "target"
                    )
                )
            )

            if not target:

                return ActionResult(
                    success=False,
                    skill="GRASP",
                    message=(
                        "GRASP requires "
                        "a target"
                    ),
                )

            print(
                "Normalised grasp target:",
                target,
            )

            # ----------------------------------------------
            # GRASP PRECONDITION
            # ----------------------------------------------
            #
            # The Task 3 planner may generate:
            #
            #     SEARCH
            #     APPROACH
            #     GRASP
            #
            # without explicitly generating REACH.
            #
            # GRASP therefore checks whether the physical
            # pre-grasp condition has already been achieved.
            #
            # If not, Task 4 automatically performs REACH
            # before attempting the grasp.

            if (
                self.robot.current_object
                != target
            ):

                print(
                    "\nGRASP precondition "
                    "not yet satisfied."
                )

                print(
                    "Automatically executing "
                    f"REACH({target})..."
                )

                reach_result = (
                    self.robot.reach(
                        target
                    )
                )

                if not reach_result.success:

                    return ActionResult(
                        success=False,
                        skill="GRASP",
                        message=(
                            "Could not reach "
                            f"{target} before "
                            "grasp"
                        ),
                        error=(
                            reach_result.error
                        ),
                    )

                print(
                    "Automatic REACH "
                    "completed successfully."
                )

            # ----------------------------------------------
            # Recovery-enabled grasp
            # ----------------------------------------------

            result = (
                self.robot.grasp_with_recovery(
                    target
                )
            )

            if result.success:

                self.last_grasped_object = (
                    target
                )

                print(
                    "Executor recorded "
                    "grasped object:",
                    self.last_grasped_object,
                )

            return result

        # ==================================================
        # MOVE_TO
        # ==================================================

        if skill == "MOVE_TO":

            target = (
                self.normalise_target_name(
                    action.get(
                        "target"
                    )
                )
            )

            if not target:

                return ActionResult(
                    success=False,
                    skill="MOVE_TO",
                    message=(
                        "MOVE_TO requires "
                        "a target"
                    ),
                )

            print(
                "Normalised transport target:",
                target,
            )

            result = (
                self.robot.move_to(
                    target
                )
            )

            if result.success:

                self.last_target_region = (
                    target
                )

            return result

        # ==================================================
        # PLACE
        # ==================================================

        if skill == "PLACE":

            # Task 3 may express PLACE using either:
            #
            # Format A:
            # {
            #     "skill": "PLACE",
            #     "object": "box",
            #     "target": "red_area"
            # }
            #
            # Format B:
            # {
            #     "skill": "PLACE",
            #     "target": "box",
            #     "location": "red_area"
            # }
            #
            # Task 4 resolves both formats into:
            #
            #     object_name = "box"
            #     target = "red_area"

            raw_object = action.get(
                "object"
            )

            raw_target = action.get(
                "target"
            )

            raw_location = action.get(
                "location"
            )

            print(
                "Raw PLACE object:",
                raw_object,
            )

            print(
                "Raw PLACE target:",
                raw_target,
            )

            print(
                "Raw PLACE location:",
                raw_location,
            )

            # ----------------------------------------------
            # Resolve destination first
            # ----------------------------------------------

            target = None

            # If Task 3 explicitly supplies "location",
            # this is the clearest destination field.
            if raw_location is not None:

                candidate = (
                    self.normalise_target_name(
                        raw_location
                    )
                )

                if candidate == "red_area":

                    target = candidate

            # Otherwise check whether "target" actually
            # contains a target region.
            if (
                target is None
                and raw_target is not None
            ):

                candidate = (
                    self.normalise_target_name(
                        raw_target
                    )
                )

                if candidate == "red_area":

                    target = candidate

            # If neither field provides a valid region,
            # use the region reached by MOVE_TO.
            if target is None:

                target = (
                    self.last_target_region
                )

            # ----------------------------------------------
            # Resolve object
            # ----------------------------------------------

            object_name = None

            # Preferred explicit object field.
            if raw_object is not None:

                candidate = (
                    self.normalise_object_name(
                        raw_object
                    )
                )

                if candidate in (
                    "box",
                    "cylinder",
                    "stone",
                ):

                    object_name = candidate

            # Some Task 3 plans put the object inside
            # "target" and destination inside "location".
            if (
                object_name is None
                and raw_target is not None
            ):

                candidate = (
                    self.normalise_object_name(
                        raw_target
                    )
                )

                if candidate in (
                    "box",
                    "cylinder",
                    "stone",
                ):

                    object_name = candidate

            # Finally, use physical execution context.
            #
            # This is particularly reliable because Task 4
            # knows which object was actually grasped.
            if (
                self.last_grasped_object
                is not None
            ):

                object_name = (
                    self.last_grasped_object
                )

            # ----------------------------------------------
            # Validate
            # ----------------------------------------------

            if object_name is None:

                return ActionResult(
                    success=False,
                    skill="PLACE",
                    message=(
                        "PLACE could not determine "
                        "which object to place"
                    ),
                )

            if target is None:

                return ActionResult(
                    success=False,
                    skill="PLACE",
                    message=(
                        "PLACE could not determine "
                        "the destination"
                    ),
                )

            print(
                "Resolved PLACE object:",
                object_name,
            )

            print(
                "Resolved PLACE target:",
                target,
            )

            # ----------------------------------------------
            # Execute
            # ----------------------------------------------

            result = (
                self.robot.place(
                    object_name,
                    target,
                )
            )

            if result.success:

                self.last_placed_object = (
                    object_name
                )

                self.last_target_region = (
                    target
                )

            return result
            # ------------------------------------------------
            # Target
            # ------------------------------------------------

            target = (
                self.normalise_target_name(
                    action.get(
                        "target"
                    )
                )
            )

            # If Task 3 omits the target, use the most
            # recent successful MOVE_TO target.

            if not target:

                target = (
                    self.last_target_region
                )

            # ------------------------------------------------
            # Validate
            # ------------------------------------------------

            if not object_name:

                return ActionResult(
                    success=False,
                    skill="PLACE",
                    message=(
                        "PLACE requires an "
                        "object and no "
                        "previously grasped "
                        "object is available"
                    ),
                )

            if not target:

                return ActionResult(
                    success=False,
                    skill="PLACE",
                    message=(
                        "PLACE requires "
                        "a target"
                    ),
                )

            print(
                "Resolved place object:",
                object_name,
            )

            print(
                "Resolved place target:",
                target,
            )

            result = (
                self.robot.place(
                    object_name,
                    target,
                )
            )

            if result.success:

                self.last_placed_object = (
                    object_name
                )

                self.last_target_region = (
                    target
                )

            return result

        # ==================================================
        # VERIFY
        # ==================================================

        if skill == "VERIFY":

            return self.execute_verify(
                action
            )

        # ==================================================
        # STOP
        # ==================================================

        if skill == "STOP":

            reason = action.get(
                "reason",
                "Task completed",
            )

            return self.robot.stop(
                reason
            )

        # ==================================================
        # UNKNOWN SKILL
        # ==================================================

        return ActionResult(
            success=False,
            skill=skill,
            message=(
                f"Unsupported Task 4 "
                f"skill: {skill}"
            ),
        )

    # ======================================================
    # VERIFY DISPATCH
    # ======================================================

    def execute_verify(
        self,
        action,
    ):
        """
        Execute an explicit VERIFY action.

        Supports verification of:

            GRASP
            PLACE

        If verify_type is omitted, infer the intended
        verification from execution context.
        """

        verify_type = action.get(
            "verify_type"
        )

        if verify_type is not None:

            verify_type = (
                str(
                    verify_type
                )
                .strip()
                .upper()
            )

        # ==================================================
        # EXPLICIT GRASP VERIFICATION
        # ==================================================

        if verify_type == "GRASP":

            object_name = (
                self.normalise_object_name(
                    action.get(
                        "object"
                    )
                )
            )

            if not object_name:

                object_name = (
                    self.last_grasped_object
                )

            if not object_name:

                return ActionResult(
                    success=False,
                    skill="VERIFY",
                    message=(
                        "Cannot verify grasp: "
                        "no object specified "
                        "or previously grasped"
                    ),
                )

            return (
                self.robot.verify_grasp(
                    object_name
                )
            )

        # ==================================================
        # EXPLICIT PLACE VERIFICATION
        # ==================================================

        if verify_type == "PLACE":

            object_name = (
                self.normalise_object_name(
                    action.get(
                        "object"
                    )
                )
            )

            target = (
                self.normalise_target_name(
                    action.get(
                        "target"
                    )
                )
            )

            if not object_name:

                object_name = (
                    self.last_placed_object
                    or
                    self.last_grasped_object
                )

            if not target:

                target = (
                    self.last_target_region
                )

            if not object_name:

                return ActionResult(
                    success=False,
                    skill="VERIFY",
                    message=(
                        "Cannot verify place: "
                        "no object available"
                    ),
                )

            if not target:

                return ActionResult(
                    success=False,
                    skill="VERIFY",
                    message=(
                        "Cannot verify place: "
                        "no target available"
                    ),
                )

            return (
                self.robot.verify_place(
                    object_name,
                    target,
                )
            )

        # ==================================================
        # INFER VERIFICATION TYPE
        # ==================================================

        # If an object has just been placed, prefer PLACE
        # verification.

        if (
            self.last_placed_object
            is not None
        ):

            object_name = (
                self.last_placed_object
            )

            target = (
                self.last_target_region
            )

            if target is None:

                return ActionResult(
                    success=False,
                    skill="VERIFY",
                    message=(
                        "Cannot infer place "
                        "verification target"
                    ),
                )

            return (
                self.robot.verify_place(
                    object_name,
                    target,
                )
            )

        # Otherwise verify the most recently grasped object.

        if (
            self.last_grasped_object
            is not None
        ):

            return (
                self.robot.verify_grasp(
                    self.last_grasped_object
                )
            )

        return ActionResult(
            success=False,
            skill="VERIFY",
            message=(
                "VERIFY could not infer "
                "what should be checked"
            ),
        )

    # ======================================================
    # COMPLETE PLAN EXECUTION
    # ======================================================

    def execute_plan(
        self,
        plan,
    ):
        """
        Execute an entire structured Task 3 plan.

        Execution stops immediately if an action fails.

        Physical GRASP and PLACE behaviours perform their
        own closed-loop verification even if Task 3 does
        not explicitly generate VERIFY actions.
        """

        print(
            "\n"
            + "=" * 65
        )

        print(
            "TASK 4 — STRUCTURED PLAN EXECUTION"
        )

        print(
            "=" * 65
        )

        # --------------------------------------------------
        # Reset execution context
        # --------------------------------------------------

        self.last_grasped_object = None
        self.last_target_region = None
        self.last_placed_object = None
        self.execution_results = []

        # --------------------------------------------------
        # Validate plan
        # --------------------------------------------------

        if not isinstance(
            plan,
            dict,
        ):

            return ExecutionReport(
                success=False,
                completed_actions=0,
                total_actions=0,
                failure_reason=(
                    "Plan must be "
                    "a dictionary"
                ),
            )

        feasible = plan.get(
            "feasible",
            True,
        )

        if not feasible:

            reason = plan.get(
                "reason",
                (
                    "Task 3 marked plan "
                    "as infeasible"
                ),
            )

            self.robot.safe_stop(
                reason
            )

            return ExecutionReport(
                success=False,
                completed_actions=0,
                total_actions=0,
                failure_reason=reason,
            )

        actions = plan.get(
            "actions",
            [],
        )

        if not isinstance(
            actions,
            list,
        ):

            return ExecutionReport(
                success=False,
                completed_actions=0,
                total_actions=0,
                failure_reason=(
                    "Plan actions must "
                    "be a list"
                ),
            )

        if not actions:

            return ExecutionReport(
                success=False,
                completed_actions=0,
                total_actions=0,
                failure_reason=(
                    "Plan contains no actions"
                ),
            )

        # --------------------------------------------------
        # Start MuJoCo viewer
        # --------------------------------------------------

        self.start()

        completed_actions = 0

        final_placement_error = None

        # ==================================================
        # EXECUTE ACTIONS
        # ==================================================

        for index, action in enumerate(
            actions,
            start=1,
        ):

            print(
                "\n"
                + "=" * 65
            )

            print(
                f"ACTION "
                f"{index}/"
                f"{len(actions)}"
            )

            print(
                "=" * 65
            )

            result = (
                self.execute_action(
                    action
                )
            )

            self.execution_results.append(
                result
            )

            print(
                "\n--- ACTION RESULT ---"
            )

            print(
                "Success:",
                result.success,
            )

            print(
                "Skill:",
                result.skill,
            )

            print(
                "Message:",
                result.message,
            )

            print(
                "Error:",
                result.error,
            )

            # ----------------------------------------------
            # FAILURE
            # ----------------------------------------------

            if not result.success:

                reason = (
                    result.message
                )

                self.robot.safe_stop(
                    (
                        f"{result.skill} "
                        f"failed: "
                        f"{reason}"
                    )
                )

                return ExecutionReport(
                    success=False,
                    completed_actions=(
                        completed_actions
                    ),
                    total_actions=len(
                        actions
                    ),
                    results=(
                        self.execution_results.copy()
                    ),
                    failure_reason=reason,
                    final_placement_error=(
                        final_placement_error
                    ),
                    grasp_attempts=(
                        self.robot.grasp_attempts
                    ),
                )

            # ----------------------------------------------
            # SUCCESSFUL ACTION
            # ----------------------------------------------

            completed_actions += 1

            # PLACE and VERIFY PLACE may both provide the
            # final XY placement error.

            if (
                result.error
                is not None
                and result.skill
                in (
                    "PLACE",
                    "VERIFY",
                )
            ):

                final_placement_error = (
                    float(
                        result.error
                    )
                )

        # ==================================================
        # PLAN COMPLETED
        # ==================================================

        print(
            "\n"
            + "=" * 65
        )

        print(
            "TASK 4 PLAN EXECUTION "
            "SUCCESSFUL"
        )

        print(
            "=" * 65
        )

        return ExecutionReport(
            success=True,
            completed_actions=(
                completed_actions
            ),
            total_actions=len(
                actions
            ),
            results=(
                self.execution_results.copy()
            ),
            failure_reason=None,
            final_placement_error=(
                final_placement_error
            ),
            grasp_attempts=(
                self.robot.grasp_attempts
            ),
        )